# A base "src" não é o ideal para o Next.js na Netlify,
# pois o netlify.toml e o package.json devem estar na raiz.
# A configuração correta é feita pelo plugin do Next.js,
# que deve encontrar a pasta 'src' automaticamente se a estrutura estiver correta.
# Vamos remover a base e garantir que o resto esteja correto.
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
